fixes for Mingw GCC
-move the .c file before -l linking libs, or else the .c will error with
"undefined reference to" to all perl symbols (-l/.o order matters on GCC)
-since HasCompiler doesn't use dlltool or .def files for GCC, use dllexport
otherwise "panic: no address for '__ANON__::__ANON__' in
'C:\WINDOWS\TEMP\0qkIOPAwix\Umwr4g3fpR.c' at lib/ExtUtils/HasCompiler.pm
line 148." since the generated .dll has no exports